[[personal-information]]
ifdef::backend-html5[]
== icon:user[] Personal Information
endif::[]

ifdef::backend-pdf[]
== Personal Information
endif::[]

Contacts::
icon:envelope[] **Email:** {email} +
icon:phone[] **Phone:** {telephone} +
icon:skype[] **Skype:** {skype-id} +
icon:map-marker[] **Location:** link:https://goo.gl/maps/CVjggk7kCeM2[{whereami}, role="external", window="_blank"]

Social Media / Websites::
https://github.com/fabioluciano[ icon:github[] Github  , role="external", window="_blank"] | https://www.linkedin.com/in/fabioluciano[ icon:linkedin[] LinkedIn , role="external", window="_blank"] | https://twitter.com/fabioluciano[ icon:twitter[] Twitter  , role="external", window="_blank"] | https://t.me/fabioluciano[ icon:comment[] Telegram , role="external", window="_blank"] +
https://log.fabioluciano.dev[Personal Blog] - Blog where I discuss topics related to software development and solutions using open source tools; +
https://fabioluciano.dev[Resume] - This project's target page, which uses AsciiDoc, Python, Docker, and Shell Script to build the resume; +
https://integr8.me[Integr8] - Open source project focused on implementing continuous integration / deployment / quality pipelines; +
https://inputs.fabioluciano.dev[Inputs] - Project for sharing open source electronics (keyboards, switches, and keycaps).
