name: 'Setup Typst with Fonts'
description: 'Install Typst and required fonts (Nerd Fonts, Liberation)'
author: 'Fabio Luciano'

runs:
  using: 'composite'
  steps:
    - name: Setup Typst
      uses: typst-community/setup-typst@v3
      with:
        typst-version: latest

    - name: Install Nerd Fonts
      shell: bash
      run: |
        # Create fonts directory
        mkdir -p ~/.local/share/fonts

        # Download and install Symbols Nerd Font (required for icons)
        wget -q https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/NerdFontsSymbolsOnly.zip -O /tmp/symbols.zip
        unzip -q /tmp/symbols.zip -d /tmp/symbols/
        cp /tmp/symbols/*.ttf ~/.local/share/fonts/ || true

        # Download and install Liberation fonts (fallback)
        sudo apt-get update -qq
        sudo apt-get install -y fonts-liberation fonts-dejavu fonts-noto-core

        # Refresh font cache
        fc-cache -fv
