
ifdef::backend-html5[]
== icon:certificate[] Certificações
endif::[]

ifdef::backend-pdf[]
== Certificações
endif::[]

--
**AWS Certified Solutions Architect** - Associate +
icon:building[title="Emissor"] Amazon Web Services icon:calendar[title="Período"] 10/2018 - 10/2023 icon:key[title="Licença"] {link-certification-aws}[EZE0CYJ2KB4QQ094, role="external", window="_blank"]
--

--
**AWS Certified Cloud Practitioner** +
icon:building[title="Emissor"] Amazon Web Services icon:calendar[title="Período"] 09/2018 - 09/2020 icon:key[title="Licença"] {link-certification-aws}[KZMW4WL21B44QN94, role="external", window="_blank"]
--

--
**LPIC-OT DevOps Tools Engineer** +
icon:building[title="Emissor"] Linux Professional Institute icon:calendar[title="Período"] 09/2018 - 09/2023 icon:key[title="Licença"] {link-certification-lpic-ot-site}[LPI000397664, role="external", window="_blank"]
--

--
**Zend Certified PHP Engineer** +
icon:building[title="Emissor"] Zend Technologies icon:calendar[title="Período"] 02/2016 - ∞ icon:key[title="Licença"] {link-certification-zend-site}[ZEND026303, role="external", window="_blank"]
--

--
**LPIC1 – Linux Professional Institute Certified** – Level 1 +
icon:building[title="Emissor"] Linux Professional Institute icon:calendar[title="Período"] 03/2012 - ∞ icon:key[title="Licença"]{link-certification-lpic-ot-site}[LPI000397664, role="external", window="_blank"]
--