  
ifdef::backend-html5[]
== icon:certificate[] Certificações
endif::[]

ifdef::backend-pdf[]
== Certificações
endif::[]

--
**Certified Kubernetes Administrator** +
icon:building[title="Emissor"] Cloud Native Computing Foundation icon:calendar[title="Período"] 10/2024 - 10/2026 icon:key[title="Licença"] {link-certification-cncf}[LF-3p8x4h8k9y, role="external", window="_blank"]
--

--
**Certified Kubernetes Application Developer** +
icon:building[title="Emissor"] Cloud Native Computing Foundation icon:calendar[title="Período"] 09/2024 - 09/2026 icon:key[title="Licença"] {link-certification-cncf}[LF-5offxxtx08, role="external", window="_blank"]
--

--
**Kubernetes and Cloud Native Security Associate** +
icon:building[title="Emissor"] Cloud Native Computing Foundation icon:calendar[title="Período"] 11/2024 - 11/2026 icon:key[title="Licença"] {link-certification-cncf}[LF-dmz92j500k, role="external", window="_blank"]
--

--
**Kubernetes and Cloud Native Associate** +
icon:building[title="Emissor"] Cloud Native Computing Foundation icon:calendar[title="Período"] 10/2024 - 10/2026 icon:key[title="Licença"] {link-certification-cncf}[LF-ave7twx7wn, role="external", window="_blank"]
--

--
**AWS Certified Solutions Architect** - Associate +
icon:building[title="Emissor"] Amazon Web Services icon:calendar[title="Período"] 10/2018 - 10/2023 icon:key[title="Licença"] {link-certification-aws}[EZE0CYJ2KB4QQ094, role="external", window="_blank"]
--

--
**AWS Certified Cloud Practitioner** +
icon:building[title="Emissor"] Amazon Web Services icon:calendar[title="Período"] 09/2018 - 09/2020 icon:key[title="Licença"] {link-certification-aws}[KZMW4WL21B44QN94, role="external", window="_blank"]
--

--
**LPIC-OT DevOps Tools Engineer** +
icon:building[title="Emissor"] Linux Professional Institute icon:calendar[title="Período"] 09/2018 - 09/2023 icon:key[title="Licença"] {link-certification-lpic-ot-site}[LPI000397664, role="external", window="_blank"]
--

--
**Zend Certified PHP Engineer** +
icon:building[title="Emissor"] Zend Technologies icon:calendar[title="Período"] 02/2016 - ∞ icon:key[title="Licença"] {link-certification-zend-site}[ZEND026303, role="external", window="_blank"]
--

--
**LPIC1 – Linux Professional Institute Certified** – Level 1 +
icon:building[title="Emissor"] Linux Professional Institute icon:calendar[title="Período"] 03/2012 - ∞ icon:key[title="Licença"]{link-certification-lpic-ot-site}[LPI000397664, role="external", window="_blank"]
--
