[[opensource]]

ifdef::backend-html5[]
== icon:code[] Open Source
endif::[]

ifdef::backend-pdf[]
== Open Source
endif::[]


=== Documentação do PHP
Participo do {link-phppeople}[time oficial de tradutores] da documentação do PHP. Para garantir que todos tivessem acesso a criar merge requests no repositório oficial, criamos um {link-phpdocbridge}[repositório] no Github que faz a ponte entre os repositórios. Para ver a lista de minhas contribuições, acesse a página de {link-phpdoc-tranlation-page}[status da documentação].

=== Imagens Docker
Todos os recursos criados estão disponíveis no {link-docker-hub-integr8}[DockerHub]. Aqui estão listados apenas alguns.
[width="100%", options="header",frame="all"] 
|===
| Nome | Descrição | Documentação 
include::../../resources/data/docker.adoc[]
|===

=== Terraform Scripts

Todos os recursos criados estão disponíveis no {link-terraform-integr8}[registrador oficial] da ferramenta. Aqui estão listados apenas alguns.

[width="100%", options="header",frame="all"] 
|===
| Nome | Descrição | Documentação 
include::../../resources/data/terraform.adoc[]
|===

=== Ansible Galaxy Roles
Todos os recursos criados estão disponíveis no {link-ansible-galaxy-fabioluciano}[Ansible Galaxy]. Aqui estão listados apenas alguns.

[width="100%", options="header",frame="all"] 
|===
| Nome | Descrição | Documentação 
include::../../resources/data/ansible.adoc[]
|===

=== Packer
[width="100%", options="header",frame="all"] 
|===
| Nome | Descrição | Documentação 
include::../../resources/data/packer.adoc[]
|===