name: build-resume-and-deploy
on:
  workflow_run:
    workflows: ["semantic-release"]
    types:
      - completed
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  create-html-files:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor
    steps:
      - uses: actions/checkout@v4
      - name: Create ptbr(default) resume version
        run: |
          asciidoctor -o ./output/index.html -a toc=left -a docinfo=shared src/resume-ptbr.adoc
      - name: Create en resume version
        run: |
          asciidoctor -o ./output/en/index.html -a toc=left -a docinfo=shared src/resume-en.adoc
      - name: Send generated output files to cache
        uses: actions/upload-artifact@v4
        with:
          name: output-html
          path: output
          overwrite: true

  create-pdf-files:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor
    steps:
      - uses: actions/checkout@v4
      - name: Create ptbr(default) resume version
        run: |
          asciidoctor-pdf -a allow-uri-read -a pdf-theme=src/resources/themes/default-theme.yml -a pdf-fontsdir=src/resources/fonts -o ./output/resume-raw.pdf src/resume-ptbr.adoc
      - name: Create en resume version
        run: |
          asciidoctor-pdf -a allow-uri-read -a pdf-theme=src/resources/themes/default-theme.yml -a pdf-fontsdir=src/resources/fonts -o ./output/en/resume-raw.pdf src/resume-en.adoc
      - name: Create ptbr(default) condensed resume version
        run: |
          asciidoctor-pdf -a with_activities=false -a allow-uri-read -a pdf-theme=src/resources/themes/default-theme.yml -a pdf-fontsdir=src/resources/fonts -o ./output/resume-condensed-raw.pdf src/resume-ptbr.adoc
      - name: Create en condensed resume version
        run: |
          asciidoctor-pdf -a with_activities=false -a allow-uri-read -a pdf-theme=src/resources/themes/default-theme.yml -a pdf-fontsdir=src/resources/fonts -o ./output/en/resume-condensed-raw.pdf src/resume-en.adoc
      - name: Send generated output files to cache
        uses: actions/upload-artifact@v4
        with:
          name: output-pdf
          path: output
          overwrite: true

  optimize-pdf:
    runs-on: ubuntu-latest
    needs: create-pdf-files
    steps:
      - name: Recover generated files from cache
        uses: actions/download-artifact@v4
        with:
          name: output-pdf
          path: output
      - name: Compress ptbr(dafault) version PDF
        uses: jy95/ghostscript-action@v1
        with:
          file: "output/resume-raw.pdf"
          output: "output/resume.pdf"
          arbitrary-parameters: "-sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dPrinted=false -dNOPAUSE -dQUIET -dBATCH"
      - name: Compress ptbr(dafault) consensed version PDF
        uses: jy95/ghostscript-action@v1
        with:
          file: "output/resume-condensed-raw.pdf"
          output: "output/resume-condensed.pdf"
          arbitrary-parameters: "-sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dPrinted=false -dNOPAUSE -dQUIET -dBATCH"
      - name: Compress english version PDF
        uses: jy95/ghostscript-action@v1
        with:
          file: "output/en/resume-raw.pdf"
          output: "output/en/resume.pdf"
          arbitrary-parameters: "-sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dPrinted=false -dNOPAUSE -dQUIET -dBATCH"
      - name: Compress en consensed version PDF
        uses: jy95/ghostscript-action@v1
        with:
          file: "output/en/resume-condensed-raw.pdf"
          output: "output/en/resume-condensed.pdf"
          arbitrary-parameters: "-sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dPrinted=false -dNOPAUSE -dQUIET -dBATCH"
      - name: Send generated output files to cache
        uses: actions/upload-artifact@v4
        with:
          name: output-pdf
          path: output
          overwrite: true

  publish-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - create-html-files
      - optimize-pdf
    steps:
      - name: Recover generated html files from cache
        uses: actions/download-artifact@v4
        with:
          name: output-html
          path: output
      - name: Recover generated pdf files from cache
        uses: actions/download-artifact@v4
        with:
          name: output-pdf
          path: output
          merge-multiple: true

      - name: Remove transient PDF version
        run: rm output/resume-raw.pdf output/en/resume-raw.pdf ./output/resume-condensed-raw.pdf ./output/en/resume-condensed-raw.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "output"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
